### ISSUE TITLE
How to enforce version checking on package install?

### ISSUE THREAD

**Issue by clarkfitzg** [duncantl/CodeAnalysis#3]
I've been using the recent changes to rstatic that @nick-ulle has made, and I'd like to make sure CodeAnalysis has the correct version of rstatic.

I added this line to the DESCRIPTION:
```
Imports: CodeDepends, rstatic (>= 0.0.0.9052)
```
This versioning doesn't seem to be enforced when I run `R CMD INSTALL` from the command line, when I load the package with `library`, or when I call the functions that use `rstatic::`. That is, I change the line to require `rstatic (>= 1.0)`, which doesn't exist, and R never complains that I don't have that version.

This happens with R 3.5.3 on my local Mac, and R 3.6.0 on Linux.

The R Extensions manual has a [section on package dependencies](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Package-Dependencies) that says:

> Version requirements can be specified and are checked when the namespace is loaded (since R >= 3.0.0).

What am I doing wrong?

**Comment by gmbecker** [comment]
Clark,

Your namespace doesn't ever actually import rstatic, which means that
loadNamespace will never hit rstatic at all, and thus never care about your
declared version dependency.

:: doesn't care about  what your package's namespace is doing because it is
an alternate way of loading the namespace directly, rather during package
load.

Adding import(rstatic) to your namespace should fix your problem, I expect.

Best,
~G

**Comment by clarkfitzg** [comment]
Thanks Gabe. It was enough to just import one function from rstatic. Fixed in https://github.com/duncantl/CodeAnalysis/commit/bceb2528dab67be7d8dc6baeaba620f3e771ca9f
